### ISSUE TITLE
Suggestion: use sticky PR comment for tldr-bot

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr#13754]
If a PR gets a lot of updates, it will sometimes also get a lot of comments via tldr-bot.
I recently found https://github.com/marocchino/sticky-pull-request-comment, which creates one comment which can be updated during the PR. 

Before I open a PR to introduce it, I would like to check if others think this might be useful.
If we want to use this, the below is what needs to be added in the `ci.yml`. Next we should tweak the `test.sh` a little.

```yml
permissions:
  pull-requests: write

uses: marocchino/sticky-pull-request-comment@v2
with:
  header: tldr-bot
  hide_and_recreate: true
  hide_classify: "OUTDATED"
  path: tldr-bot.md
```

```bash
# Additional checks for GitHub Actions pull request builds.
# Only taken as suggestions, does not make the build fail.
function run_checks_pr {
  msgs=$(bash scripts/check-pr.sh)

  if [[ -n $msgs ]]; then
    echo -e "\nCheck PR reported the following message(s):\n$msgs\n" >&2
    echo 'Sending check results to PR.' >&2
    echo -n "$msgs" > tldr-bot.md
  fi
}
