### ISSUE TITLE
the formatting of the `tldr` is better than the formatting of any tldr client (e.g. `tlrc`, `tealdeer`)

### ISSUE THREAD

**Issue by demo-err** [tldr-pages/tldr#16821]
the newlines after each command definition (e.g. "`- Open a file:`") before each command example (e.g. "`helix path/to/file`") are waste of space and unnecessary. it would be cleaner and terminal space efficient if those newlines are non-existent. using tldr without a client displays better formatting but is slower.

# `tldr`

![Image](https://github.com/user-attachments/assets/d60f2bce-e05f-43de-af02-07aa81828da5)

# `tlrc`
![Image](https://github.com/user-attachments/assets/05fa9450-e7fa-4273-a297-aa158016342d)

**Comment by acuteenvy** [comment]
> the newlines after each command definition are a waste of space and unnecessary

"Better formatting" is very subjective. You can remove the newlines in tlrc by setting `compact = true` in the config, but that option removes all empty lines, not just those between the example and its description. I guess we could change that, but someone else might think the current formatting is better.

Here's a tlrc config that looks similar to the Python client:
```toml
[output]
show_hyphens = true
compact = true

[style.title]
color = "default"
bold = true

[style.description]
color = "default"

[style.bullet]
color = "green"

[style.example]
color = "red"

[style.placeholder]
color = "default"
```

![screenshot-tldr-helix](https://github.com/user-attachments/assets/dcbfb0fd-c051-4cd0-858d-e633e81e63ba)
